image: alpine:latest

stages:
  - build
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - target
    - $CARGO_HOME
    - web/node_modules
    - web/.cache

web:
  image: node:latest
  stage: build
  script:
    - cd web
    - yarn
    - cp -r node_modules/@fortawesome/fontawesome-free/webfonts ../webfonts
    # bundle css
    - yarn run parcel build -d ../static -o custom.css --no-source-maps index.scss
  artifacts:
    paths:
      - static

cargo_build:
  image: rust:1.33
  stage: build
  script:
    # compile rust
    - cargo install cargo-web --quiet || true
    - cargo web build --release
    - mv target/wasm32-unknown-unknown/release/remap.js static
    - mv target/wasm32-unknown-unknown/release/remap.wasm static
  artifacts:
    paths:
      - static

pages:
  stage: deploy
  only: 
    - master
  variables:
    ACME_CHALLENGE: ''
    ACME_FILE: 'noop'
  script:
    # copy dist to public dir
    - cp -r static public
    # make acme challenge
    - mkdir -p public/.well-known/acme-challenge/
    - echo $ACME_CHALLENGE > public/.well-known/acme-challenge/$ACME_FILE
  artifacts:
    paths:
      - public

