image: alpine:latest

stages:
  - build
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

cache:
  paths:
    - target
    - $CARGO_HOME
    - web/node_modules
    - web/.cache

web:
  image: node:latest
  stage: build
  script:
    - cd web
    - yarn
    - cp -r node_modules/@fortawesome/fontawesome-free/webfonts ../static/webfonts
    # bundle css
    - yarn run sass --no-source-map -s compressed index.scss ../static/custom.css
  artifacts:
    paths:
      - static

cargo_build:
  image: rust:1.39
  stage: build
  script:
    # compile rust
    - cargo install wasm-pack --quiet || true
    - cargo/bin/wasm-pack build -t web -d static/pkg
  artifacts:
    paths:
      - static/pkg

pages:
  stage: deploy
  only: 
    - master
  script:
    - mv static public
  artifacts:
    paths:
      - public

